spring:
       datasource:
                  url: jdbc:mysql://localhost:3306/skillgrid
                  driver-class-name: com.mysql.jdbc.Driver
                  username: root
                  password: root